#!/usr/bin/env sh

set -e

export DOCC_JSON_PRETTYPRINT="YES"

mkdir -p docs

swift package --allow-writing-to-directory docs \
    generate-documentation --target Fakes \
    --disable-indexing \
    --transform-for-static-hosting \
    --hosting-base-path 'swift-fakes' \
    --output-path docs
